In [1]:
print("hello")

hello


In [4]:

  
# Read and store content
# of an excel file 
read_file = pd.read_excel ("Test.xlsx")
  


In [5]:
# Write the dataframe object
# into csv file
read_file.to_csv ("Test.csv", 
                  index = None,
                  header=True)
    

In [6]:
# read csv file and convert 
# into a dataframe object
df = pd.DataFrame(pd.read_csv("Test.csv"))

In [7]:
# show the dataframe
df

,Sr. No.,Name,ID,Cost
0,1,Jeenie,54542,10.22
1,2,Alex,55116,55.00
2,3,Bob,78866,66.55
3,4,Ronald,66525,55.44
4,5,Jacob,35153,515.50
5,6,Chan,65165,5153.50
6,7,Ron,32131,515.50
7,8,Becky,78954,513.50


In [3]:
import numpy as np
import pandas as pd

In [9]:
data = np.random.rand(1000000)

In [10]:
data

array([0.51553843, 0.50675647, 0.46638302, ..., 0.64999275, 0.05521412,
       0.79936947])

In [11]:
minV,maxV,sd= np.min(data),np.max(data),np.std(data)

In [12]:
sd

0.2885728019989056

In [14]:
data.max()

0.9999965782708619

In [15]:
data2 = np.random.rand(4,8)

In [16]:
data2

array([[0.1444745 , 0.89133852, 0.26726518, 0.99666777, 0.36622427,
        0.42364337, 0.57260693, 0.73821026],
       [0.24543116, 0.58575669, 0.52767111, 0.23273594, 0.24908748,
        0.38284566, 0.94445891, 0.64695116],
       [0.94931463, 0.38145458, 0.83999405, 0.96153561, 0.79355865,
        0.24159722, 0.57929185, 0.93431698],
       [0.28316429, 0.41208055, 0.85032564, 0.76569089, 0.53482812,
        0.22873078, 0.28367042, 0.00961903]])

In [19]:
np.mean(data2,axis=0)

array([0.40559615, 0.56765758, 0.621314  , 0.73915755, 0.48592463,
       0.31920426, 0.59500703, 0.58227436])

In [20]:
np.mean(data2)

0.5395169441319778

In [21]:
meanC=np.mean(data2,axis=0)

In [22]:
len(meanC)

8